#include <string>

enum class TokenType {
  IDENTIFIER_TOKEN,

  NULL_TOKEN,
  STRING_TOKEN,
  NUMBER_TOKEN,
  BOOLEAN_TOKEN,
  CHAR_TOKEN,
  FLOAT_TOKEN,
  DOUBLE_TOKEN,
  LONG_TOKEN,
  SHORT_TOKEN,
  BYTE_TOKEN,

  CONST_TOKEN,

  IF_TOKEN,
  ELSE_TOKEN,
  ELSE_IF_TOKEN,
  FOR_TOKEN,
  WHILE_TOKEN,
  DO_TOKEN,
  SWITCH_TOKEN,
  CASE_TOKEN,
  DEFAULT_TOKEN,
  RETURN_TOKEN,

  CLASS_TOKEN,
  EXTENDS_TOKEN,

  BREAK_TOKEN,
  CONTINUE_TOKEN,

  ADD_TOKEN,
  SUBTRACT_TOKEN,
  MULTIPLY_TOKEN,
  DIVIDE_TOKEN,
  EQUAL_TOKEN,
  NOT_EQUAL_TOKEN,
  GREATER_THAN_TOKEN,
  LESS_THAN_TOKEN,
  GREATER_THAN_EQUAL_TOKEN,
  LESS_THAN_EQUAL_TOKEN,
  MODULO_TOKEN,
};

class Token {
  public:
    TokenType type;
    std::string value;

    Token(TokenType type, std::string value){
      this->type = type;
      this->value = value;
    }
};